# Use official Python image
FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /code

# Install system dependencies
RUN apt-get update && apt-get install -y gcc

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy FastAPI app code
COPY app ./app

# Expose FastAPI default port
EXPOSE 8000

# Run the app with hot reload
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
